"""empty message

Revision ID: b8522ace5f42
Revises: 5db7bbd487c9
Create Date: 2021-02-22 20:24:51.633736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8522ace5f42'
down_revision = '5db7bbd487c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('nationality', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'nationality')
    # ### end Alembic commands ###
